'use client';

import { Sun } from 'lucide-react';
import TraceableValue from '../components/trace/TraceableValue';
import type { TraceabilityPayload } from '@/types/traceability';

interface HeaderProps {
  lang: 'ko' | 'en';
  onOpenTrace: (trace: TraceabilityPayload) => void;
}

const t = {
  sunny: { ko: '맑음', en: 'Sunny' },
  humidity: { ko: '습도', en: 'Humidity' },
  rain: { ko: '강수', en: 'Rain' },
  none: { ko: '없음', en: 'None' },
  cycleCompleted: { ko: '사이클 완료', en: 'CYCLE COMPLETED' },
  awaitingPlacement: { ko: '입추 대기중', en: 'AWAITING PLACEMENT' },
  thu: { ko: '목', en: 'Thu' },
};

const Header = ({ lang, onOpenTrace }: HeaderProps) => {
  const overviewMetrics: Array<{ label: string; value: string; trace: TraceabilityPayload }> = [
    {
      label: 'House(s)',
      value: 'Age 35',
      trace: {
        trace_id: 'overview:house-age',
        display_value: 'Age 35',
        logic_summary:
          lang === 'ko'
            ? '입추일(2025-12-29) 기준으로 오늘 일령을 계산했습니다.'
            : 'Age is calculated from placement date (2025-12-29).',
        logic_formula: lang === 'ko' ? '오늘일자 - 입추일자 = 35일령' : 'today - placement_date = 35 days',
        data_source: [
          {
            source_id: 'db:flock_cycle:2025-12-29',
            type: 'db',
            name: 'flock_cycle_master',
            url: 'https://p-root.local/db/flock_cycle_master?cycle=2025-12',
            row_id: 'cycle_id=2025-12',
            highlight_text: lang === 'ko' ? 'placement_date=2025-12-29' : 'placement_date=2025-12-29',
            highlight_anchor: 'cycle_id=2025-12',
          },
        ],
        is_ai_generated: false,
        source_version: 'v2026.02.11',
        snapshot_at: '2026-02-07 20:00:00',
      },
    },
    {
      label: 'Rearing Count',
      value: '6,400',
      trace: {
        trace_id: 'overview:rearing-count',
        display_value: '6,400',
        logic_summary:
          lang === 'ko'
            ? '입추 마릿수에서 누적 도태·폐사를 제외한 현재 사육 마릿수입니다.'
            : 'Current birds = placed birds - cumulative culling/mortality.',
        logic_formula: lang === 'ko' ? '6,520 - 120 = 6,400' : '6,520 - 120 = 6,400',
        data_source: [
          {
            source_id: 'db:flock_inventory:2026-02-07',
            type: 'db',
            name: 'flock_inventory_daily',
            url: 'https://p-root.local/db/flock_inventory_daily?date=2026-02-07',
            row_id: 'house=H01,date=2026-02-07',
            highlight_text: 'placed=6520, mortality=120, current=6400',
            highlight_anchor: 'house=H01,date=2026-02-07',
          },
        ],
        is_ai_generated: false,
        source_version: 'v2026.02.11',
        snapshot_at: '2026-02-07 20:00:00',
      },
    },
    {
      label: 'Survival Rate',
      value: '100%',
      trace: {
        trace_id: 'overview:survival-rate',
        display_value: '100%',
        logic_summary:
          lang === 'ko'
            ? '누적 폐사율을 기반으로 생존율을 계산하고 소수점 반올림 처리했습니다.'
            : 'Survival rate is computed from cumulative mortality with rounding.',
        logic_formula: lang === 'ko' ? '((6,400-0)/6,400)×100 = 100%' : '((6,400-0)/6,400)×100 = 100%',
        data_source: [
          {
            source_id: 'db:mortality_daily:2026-02-07',
            type: 'db',
            name: 'mortality_daily',
            url: 'https://p-root.local/db/mortality_daily?date=2026-02-07',
            row_id: 'house=H01,date=2026-02-07',
            highlight_text: 'daily_mortality=0, cumulative_mortality=0',
            highlight_anchor: 'house=H01,date=2026-02-07',
          },
        ],
        is_ai_generated: false,
        source_version: 'v2026.02.11',
        snapshot_at: '2026-02-07 20:00:00',
      },
    },
    {
      label: 'Est. Weight',
      value: '1,081g',
      trace: {
        trace_id: 'overview:estimated-weight',
        display_value: '1,081g',
        logic_summary:
          lang === 'ko'
            ? '최근 72시간 CCTV 추정치와 표준 체중 곡선을 결합해 산출한 예측값입니다.'
            : 'Estimated value generated by blending CCTV inference and standard weight curve.',
        logic_formula:
          lang === 'ko'
            ? '0.7×CCTV 추정평균(1,060g) + 0.3×표준곡선(1,130g) = 1,081g'
            : '0.7×CCTV mean(1,060g) + 0.3×standard(1,130g) = 1,081g',
        data_source: [
          {
            source_id: 'file:model-run-2026-02-07',
            type: 'file',
            name: 'weight_forecast_run_20260207.json',
            url: 'https://p-root.local/files/weight_forecast_run_20260207.json',
            highlight_text: 'blended_weight=1081',
            highlight_anchor: '$.forecast.current.weight_g',
          },
          {
            source_id: 'db:cctv_weight_hourly:2026-02-07',
            type: 'db',
            name: 'cctv_weight_hourly',
            url: 'https://p-root.local/db/cctv_weight_hourly?date=2026-02-07',
            row_id: 'house=H01,hour=11',
            highlight_text: 'mean_weight=1060',
            highlight_anchor: 'house=H01,hour=11',
          },
        ],
        is_ai_generated: true,
        source_version: 'model-2.4.1',
        snapshot_at: '2026-02-07 11:00:00',
        confidence: 0.87,
        version_history: [
          {
            source_version: 'model-2.4.0',
            snapshot_at: '2026-02-06 11:00:00',
            display_value: '1,064g',
            logic_summary:
              lang === 'ko'
                ? '이전 버전(2.4.0)에서는 CCTV 비중 0.75를 적용했습니다.'
                : 'Previous model (2.4.0) used CCTV blend weight 0.75.',
            confidence: 0.83,
            data_source: [
              {
                source_id: 'file:model-run-2026-02-06',
                type: 'file',
                name: 'weight_forecast_run_20260206.json',
                url: 'https://p-root.local/files/weight_forecast_run_20260206.json',
                highlight_text: 'blended_weight=1064',
                highlight_anchor: '$.forecast.current.weight_g',
              },
              {
                source_id: 'db:cctv_weight_hourly:2026-02-06',
                type: 'db',
                name: 'cctv_weight_hourly',
                url: 'https://p-root.local/db/cctv_weight_hourly?date=2026-02-06',
                row_id: 'house=H01,hour=11',
                highlight_text: 'mean_weight=1048',
                highlight_anchor: 'house=H01,hour=11',
              },
            ],
          },
          {
            source_version: 'model-2.3.8',
            snapshot_at: '2026-02-05 11:00:00',
            display_value: '1,041g',
            logic_summary:
              lang === 'ko'
                ? '초기 버전은 표준 체중 곡선 가중치가 더 높았습니다.'
                : 'Older version had a larger standard-curve weight.',
            confidence: 0.8,
            data_source: [
              {
                source_id: 'file:model-run-2026-02-05',
                type: 'file',
                name: 'weight_forecast_run_20260205.json',
                url: 'https://p-root.local/files/weight_forecast_run_20260205.json',
                highlight_text: 'blended_weight=1041',
                highlight_anchor: '$.forecast.current.weight_g',
              },
              {
                source_id: 'db:standard_weight_curve:v2026-02',
                type: 'db',
                name: 'standard_weight_curve',
                url: 'https://p-root.local/db/standard_weight_curve?version=v2026-02',
                row_id: 'breed=broiler-v2',
                highlight_text: 'curve_weight=1130',
                highlight_anchor: 'breed=broiler-v2',
              },
            ],
          },
        ],
      },
    },
    {
      label: 'Temp/Humid',
      value: '0°C/0%',
      trace: {
        trace_id: 'overview:temp-humid',
        display_value: '0°C/0%',
        logic_summary:
          lang === 'ko'
            ? '마지막 센서 수집 시점에서 온도·습도 값을 조합한 요약값입니다.'
            : 'Summary value from the latest temperature and humidity sensor snapshots.',
        logic_formula: lang === 'ko' ? '온도 최신값 / 습도 최신값' : 'latest temperature / latest humidity',
        data_source: [
          {
            source_id: 'db:sensor_snapshot:2026-02-07',
            type: 'db',
            name: 'sensor_snapshot_latest',
            url: 'https://p-root.local/db/sensor_snapshot_latest?house=H01',
            row_id: 'sensor_group=TH,house=H01',
            highlight_text: 'temperature=0, humidity=0',
            highlight_anchor: 'sensor_group=TH,house=H01',
          },
        ],
        is_ai_generated: false,
        source_version: 'v2026.02.11',
        snapshot_at: '2026-02-07 20:00:00',
      },
    },
  ];

  return (
    <div className="flex flex-col xl:flex-row gap-4">
      {/* Left Card - Weather Info */}
      <div className="xl:basis-[35%] flex-shrink-0 bg-[#161b22] p-3 border border-[#30363d]">
        <div className="h-full flex items-center justify-center">
          <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 w-full">
            <div className="flex items-center gap-3">
            <span className="text-2xl sm:text-3xl font-bold text-[#3fb950]">33.2°</span>
            <div className="flex items-center gap-1 text-[#3fb950]">
              <Sun className="w-4 h-4" />
              <span className="text-sm font-bold">{t.sunny[lang]}</span>
            </div>
          </div>

            <div className="h-px w-full sm:h-9 sm:w-px bg-gray-700" />

            <div className="space-y-1 min-w-0 sm:min-w-[120px] text-left">
              <div className="flex items-center justify-between gap-2 text-[11px] sm:text-sm text-gray-300 font-medium">
                <span className="min-w-0 text-left truncate">{lang === 'ko' ? '02/05(목)' : 'Thu, 02/05'}</span>
                <span className="text-gray-400 min-w-0 text-right">18:24</span>
              </div>
              <div className="text-[11px] sm:text-sm flex items-center justify-between gap-2">
                <span className="text-gray-400 min-w-0 truncate">{t.humidity[lang]}</span>
                <span className="text-[#3fb950] min-w-0 text-right">32%</span>
              </div>
              <div className="text-[11px] sm:text-sm flex items-center justify-between gap-2">
                <span className="text-gray-400 min-w-0 truncate">{t.rain[lang]}</span>
                <span className="text-[#3fb950] min-w-0 text-right">0% 0mm</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Right Card - Cycle Status */}
      <div className="flex-1 bg-[#161b22] p-3 border border-[#30363d] flex items-center justify-center">
        <div className="w-full">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between mb-4 gap-2">
            <div className="flex items-center gap-2">
              <h2 className="text-gray-400 font-medium">OVERVIEW</h2>
              <span className="px-1 py-[1px] text-[10px] font-semibold text-[#3fb950] bg-[#3fb950]/15 border border-[#3fb950]">Growing</span>
            </div>
            <div className="flex items-center flex-wrap gap-2 text-[10px] text-gray-500">
              <span>Sensors | 02.07 20:00</span>
              <span>Weight | 02.07 11:00</span>
            </div>
            </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-5 gap-3">
            {overviewMetrics.map((metric) => (
              <div key={metric.label} className="text-center">
                <p className="text-sm text-[#3fb950] font-semibold mb-1">{metric.label}</p>
                <TraceableValue
                  value={metric.value}
                  trace={metric.trace}
                  onOpenTrace={onOpenTrace}
                  align="center"
                  valueClassName="text-sm text-gray-200"
                />
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Header;
